import type { Metadata } from "next";
import "./globals.css";
import styles from "./layout.module.css";
import { Navigation } from "@/app/ui/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        <main className={styles.main}>{children}</main>
      </body>
    </html>
  );
}
